"""empty message

Revision ID: 3ffec6168224
Revises: 63095af2ba51
Create Date: 2022-11-08 16:40:26.191527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ffec6168224'
down_revision = '63095af2ba51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('course_name', sa.String(), nullable=False))
    op.add_column('lectures', sa.Column('lecture_num', sa.String(), nullable=False))
    op.drop_column('lectures', 'title')
    op.drop_column('lectures', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lectures', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('lectures', 'lecture_num')
    op.drop_column('lectures', 'course_name')
    # ### end Alembic commands ###
