"""empty message

Revision ID: d3f5ce41022f
Revises: 3ffec6168224
Create Date: 2022-11-08 16:49:59.065352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f5ce41022f'
down_revision = '3ffec6168224'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attend', sa.Column('lec_id', sa.Integer(), nullable=False))
    op.drop_constraint('attend_post_id_fkey', 'attend', type_='foreignkey')
    op.create_foreign_key(None, 'attend', 'lectures', ['lec_id'], ['id'], ondelete='CASCADE')
    op.drop_column('attend', 'post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attend', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attend', type_='foreignkey')
    op.create_foreign_key('attend_post_id_fkey', 'attend', 'lectures', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('attend', 'lec_id')
    # ### end Alembic commands ###
